# Generated by Django 5.0.4 on 2024-05-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0016_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_date',
        ),
    ]
