# Generated by Django 5.0.4 on 2024-04-30 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_alter_post_body'),
        ('members', '0002_alter_userprofile_about_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.userprofile'),
        ),
    ]
