# Generated by Django 5.0.4 on 2024-05-10 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_rename_comment_body_comment_body'),
        ('members', '0014_alter_userprofile_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='members.userprofile'),
        ),
    ]
