# Generated by Django 5.0.4 on 2024-05-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0014_remove_comment_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
