# Generated by Django 5.0.4 on 2024-05-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0017_remove_comment_comment_date'),
        ('members', '0014_alter_userprofile_about_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='members.userprofile'),
        ),
    ]
