# Generated by Django 5.0.4 on 2024-05-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0018_comment_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_profile',
            new_name='user_pic',
        ),
    ]
