# Generated by Django 5.0.4 on 2024-05-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0020_rename_user_pic_comment_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_profile',
        ),
    ]
