# Generated by Django 5.0.4 on 2024-05-15 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0024_post_likes'),
        ('members', '0015_alter_userprofile_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='members.userprofile'),
        ),
    ]
