# Generated by Django 5.0.6 on 2024-05-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0025_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
