# Generated by Django 5.0.4 on 2024-04-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_userprofile_about_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_picture',
        ),
    ]
