# Generated by Django 5.0.4 on 2024-05-04 11:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_userprofile_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_user',
            field=ckeditor.fields.RichTextField(max_length=700),
        ),
    ]
