# Generated by Django 5.0.4 on 2024-04-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_userprofile_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(default='images', upload_to='img'),
        ),
    ]
