# Generated by Django 5.0.4 on 2024-05-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_userprofile_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_user',
            field=models.TextField(max_length=1000),
        ),
    ]
