# Generated by Django 5.0.4 on 2024-05-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_userprofile_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_user',
            field=models.TextField(max_length=500),
        ),
    ]
